# The Site Configuration

theme: jekyll-theme-chirpy

baseurl: ''

lang: en

timezone: Europe/Madrid

# --------------------------

title: ISntMA                          # the main title

tagline: Blog # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  Infosec blog

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'isntma.github.io'

github:
  username: isntma             # change to your github username

social:
  name: ISntMA
  email: isnt.ma@tuta.io             # change to your email address
  links:
    - https://github.com/isntma       # change to your github homepage
    # - https://www.linkedin.com/in/username

# --------------------------

# Prefer color scheme setting.

theme_mode:   # [light|dark]

# The CDN endpoint for images.

img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/avatar.jpg

# boolean type, the global switch for ToC in posts.
toc: true

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled:     
    env:         

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: false # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
